### ISSUE TITLE
does not compile with ddc

### ISSUE THREAD

**Issue by robertmuth** [olov/dart-range#2]
[error] Invalid override. The type of 'Range.map' ('((dynamic) → dynamic) → List<dynamic>') isn't a subtype of 'IterableMixin<int>.map' ('<T>((int) → T) → Iterable<T>'). (package:range/range.dart, line 66, col 3)
[error] Invalid override. The type of 'Range.==' ('(Range) → bool') isn't a subtype of 'Object.==' ('(dynamic) → bool'). (package:range/range.dart, line 74, col 3)

**Comment by olov** [comment]
https://github.com/olov/dart-range/blob/master/README.md#this-project-has-moved

**Comment by robertmuth** [comment]
Hi Olov,

sorry to bother you but somehow it is not possible to file and issue against the branch of the new owner
which is why I filed the issue against your branch.

**Comment by olov** [comment]
Sorry to hear that. This repo is however deprecated so I won't be able to help you. I don't know how much the code has change since I left it but I would imagine that the codebase is still tiny so I recommend taking a look at it yourself.
